### ISSUE TITLE
неправльно конвертируется номер

### ISSUE THREAD

**Issue by arudmin** [leshchenko1979/gosnomer#3]
Если первая цифра - ноль, она конвертируется в букву О

`$ python`
`Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import gosnomer`
`>>> nomer = "о001тр98"`
`>>> norm  = gosnomer.normalize(nomer)`
`>>> print(nomer, norm)`
`о001тр98 ОО01ТР98`

**Comment by leshchenko1979** [comment]
Дело в том, что `OO01ТР98` - это вполне допустимый номер для мопеда :)

Я думаю, надо вводить в функцию параметр для исключения каких-то форматов.
